name: intelligence_company_ia
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  supabase_flutter: ^2.9.1
  image_picker: ^1.1.2
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  file_picker: ^8.0.0
  http: ^1.1.0
  audioplayers: ^6.0.0
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  animate_do: ^3.3.3

 
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/logo_A.png
    - assets/logos/logo_B.png
    - assets/logos/logo_C.png
    - assets/logos/logo_D.png
    - assets/auth/inicio.png
    - assets/logos/teachers.png
    - assets/logos/student.png


